### ISSUE TITLE
有没有Linux服务器自动运行的？

### ISSUE THREAD

**Issue by poshoi** [erwanjun/weixin_tuisong#14]
如题

**Comment by erwanjun** [comment]
没有噢






二万君
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "erwanjun/weixin_tuisong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 上午10:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[erwanjun/weixin_tuisong] 有没有Linux服务器自动运行的？ (Issue #14)





 
如题
