### ISSUE TITLE
config.json 暴露appID和appsecret真的没关系吗

### ISSUE THREAD

**Issue by SkywingsWang** [erwanjun/weixin_tuisong#22]
首先想说的是谢谢大佬！一次就成功了，教程写的非常详细~
其次就是有如题的担心...不知道会不会导致微信账号被盗之类的情况
之前看到过一种写法是可以把这些参数放到Setting-Secrets-Actions里面，这样既可以调用又不会暴露隐私信息，有没有可能改成这样的呢？或者将库隐藏掉，action也会自动运行的话直接隐藏掉或许比较安全

**Comment by erwanjun** [comment]
好建议，谢谢反馈
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wqangzuoshuai ***@***.***&gt;
发送时间: 2022年8月24日 19:15
收件人: erwanjun/weixin_tuisong ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[erwanjun/weixin_tuisong] config.json 暴露appID和appsecret真的没关系吗 (Issue #22)





 
首先想说的是谢谢大佬！一次就成功了，教程写的非常详细~
 其次就是有如题的担心...不知道会不会导致微信账号被盗之类的情况
 之前看到过一种写法是可以把这些参数放到Setting-Secrets-Actions里面，这样既可以调用又不会暴露隐私信息，有没有可能改成这样的呢？或者将库隐藏掉，action也会自动运行的话直接隐藏掉或许比较安全
