### ISSUE TITLE
读取config.json中各个api是否需要启用时没有读到false和true，导致实际上都启用了

### ISSUE THREAD

**Issue by excavate** [erwanjun/weixin_tuisong#26]
![image](https://user-images.githubusercontent.com/48313294/186681543-0fb6e385-4ddc-4cce-9f7b-db984c798ad1.png)
如图，这样获得的对应值都为空字符串，应改为读取实际的json值

**Comment by erwanjun** [comment]
感谢告知


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: fox ***@***.***&gt;
发送时间: 2022年8月25日 21:46
收件人: erwanjun/weixin_tuisong ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[erwanjun/weixin_tuisong] 读取config.json中各个api是否需要启用时没有读到false和true，导致实际上都启用了 (Issue #26)





 

 如图，这样获得的对应值都为空字符串，应改为读取实际的json值
